-- Tree storage: adjacency list (parent_id) + materialized path (path).
--
-- path holds the ids of all ancestors and of the node itself, e.g. '/1/4/9/'.
-- It lets us:
--   * return the full ancestor chain of a node in the same row (no recursion),
--   * soft-delete a whole subtree with a single indexed prefix query,
--     including descendants that were never loaded by the client.
-- Parent-child relationships are immutable, so the path never has to be rewritten.

CREATE TABLE IF NOT EXISTS tree_nodes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id  BIGINT      NULL REFERENCES tree_nodes (id),
    value      TEXT        NOT NULL,
    path       TEXT        NOT NULL,
    depth      INT         NOT NULL,
    is_deleted BOOLEAN     NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_tree_nodes_value_not_empty CHECK (length(btrim(value)) > 0)
);

CREATE INDEX IF NOT EXISTS ix_tree_nodes_parent_id ON tree_nodes (parent_id);

-- text_pattern_ops makes "path LIKE '/1/4/%'" an index range scan.
CREATE UNIQUE INDEX IF NOT EXISTS ux_tree_nodes_path ON tree_nodes (path text_pattern_ops);
